# Generated by Django 5.0.3 on 2024-03-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_table',
            fields=[
                ('autoincrementid', models.AutoField(primary_key=True, serialize=False)),
                ('itemcode', models.CharField(default=0, max_length=100)),
                ('Description', models.CharField(default=0, max_length=150)),
                ('Quantity', models.IntegerField()),
                ('PO_no', models.CharField(default=0, max_length=100)),
                ('MatType', models.CharField(default=0, max_length=100)),
                ('Active', models.BooleanField(default=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
