# Generated by Django 5.0.3 on 2024-03-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_table',
            old_name='itemcode',
            new_name='Itemcode',
        ),
    ]
