# Generated by Django 5.0.3 on 2024-03-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_itemcode_product_table_itemcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='Description',
            field=models.CharField(max_length=150),
        ),
    ]
