# Generated by Django 5.0.3 on 2024-03-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_table_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='Location',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
    ]
