# Generated by Django 5.0.3 on 2024-04-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_table_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='Order_by',
            field=models.CharField(default='System', max_length=100),
        ),
        migrations.AddField(
            model_name='product_table',
            name='User',
            field=models.CharField(default='System', max_length=100),
        ),
    ]
