# Generated by Django 5.0.3 on 2024-04-08 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_table_order_by_product_table_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_table',
            fields=[
                ('autoincrementid', models.AutoField(primary_key=True, serialize=False)),
                ('Hist_invoice', models.CharField(default=0, max_length=100)),
                ('Hist_description', models.CharField(max_length=150)),
                ('Hist_quantity', models.IntegerField()),
                ('Hist_ajdqty', models.IntegerField(default=0)),
                ('Hist_po', models.CharField(default=0, max_length=100)),
                ('Hist_MatType', models.CharField(default=0, max_length=100)),
                ('Active', models.BooleanField(default=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Location', models.CharField(default='Not Assigned', max_length=100)),
                ('Order_by', models.CharField(default='System', max_length=100)),
                ('User', models.CharField(default='System', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='product_table',
            old_name='Itemcode',
            new_name='InvoiceNo',
        ),
        migrations.RenameField(
            model_name='product_table',
            old_name='User',
            new_name='Received_by',
        ),
        migrations.AddField(
            model_name='product_table',
            name='Punched_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='product_table',
            name='Used_by',
            field=models.CharField(default='System', max_length=100),
        ),
    ]
