# Generated by Django 5.0.3 on 2024-04-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_history_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_table',
            name='Hist_itemcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product_table',
            name='ChallanNo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product_table',
            name='Itemcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='history_table',
            name='Hist_MatType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='history_table',
            name='Hist_invoice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='history_table',
            name='Hist_po',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='history_table',
            name='Hist_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_table',
            name='InvoiceNo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product_table',
            name='Quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
