# Generated by Django 5.0.3 on 2024-04-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_history_table_hist_itemcode_product_table_challanno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='Comments',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
